version: '3.4'

services:
  api:
    image: kmart2234/fibzy:1.0.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
        local.description: "fibzy API"
    ports:
      - 80:8001
    networks:
      - fibzy-net1
networks:
  fibzy-net1:
