version: '3.4'

services:
  fibonacci:
    image: kmart2234/fibzy:1.0.1
    ports:
      - 8001:8001
    networks:
      - fibzy-net1
    deploy:
      replicas: 5
          resources:
            limits:
              cpus: "0.1"
              memory: 50M
          restart_policy:
            condition: on-failure
      labels:
        local.description: "fibzy API"

networks:
  fibzy-net1:
